baseURL = 'https://mengo.sirapollokaggwaschools.co.ug/'
languageCode = 'en-us'
title = 'Sir Apollo Kaggwa Primary School - mengo'
theme = "C:\\Users\\timot\\SAKS_web\\sirapollokaggwaschools\\themes\\saks-theme"


[params]
logo = "/img/logo.png"
mainSchool = false
defaultDescription = "Sir Apollo Kaggwa nursery and primary school-mengo is a number one education service provider within Uganda aiming at developing a holistic child throughout the primary level."
    [params.school]
        name = "mengo"
        motto = 'Education with a Purpose'
        mission = 'To be a leading school in the provision of quality education'
        vision = 'The vision of Sir Apollo Kaggwa Primary School, mengo is to produce devoted learners in academics, moral education and life skills, leadership skills, creativity, and innovation, honest and humble, self-driven with a positive attitude towards quality work.'
        summary1 = 'Sir Apollo Kaggwa nursery and primary school-mengo is a number one education service provider within Uganda aiming at developing a holistic child throughout the primary level. The school has two sections i.e pre-school and Primary school.'
        summary2 = 'At Sir Apollo Kaggwa Primary School, mengo, we are always learning through a holistic curriculum where individual talents are celebrated and nurtured. Working together as one team, in a caring, yet stimulating environment, we ensure that as an organization, excellence is the expectation. Our network of strong pastoral support fulfills the ambitions of students so that graduates go on to make a positive difference to the world in which they live.'
        hm = "I am very pleased to write an article about Sir Apollo Kaggwa Primary School – Mengo on this website.  I thank you very much indeed for the support you rendered to this school.  I highly treasure the contribution you make towards the faster growth of this mighty school. Sir Apollo Kaggwa Primary School – Mengo"
    [params.carousel]
        two = "Offering a broad learning environment"
        three = "We train leaders by embracing smartness"
        four = "Offering the best learning skills to students"
        five = "Welcoming all types of students"
        six = "Interactive teachers that monitor pupils in all activities"
        