backend:
  name: git-gateway
  branch: main

media_folder: "static/img" # Base media folder
public_folder: "/img" # Base public folder
display_url: https://mengo.sirapollokaggwaschools.co.ug/
logo_url: https://mengo.sirapollokaggwaschools.co.ug/img/logo.png

collections:
  - name: "news"
    label: "School Events/News"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    media_folder: "/static/img/posts" # Media files for this collection will be stored in static/img/posts
    public_folder: "/img/posts" # The src attribute for uploaded media will begin with /img/posts
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", default: "", format: "YYYY-MM-DDTHH:mm:ssZ" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "about"
    label: "About Page"
    folder: "content/about"
    create: false
    slug: "index"
    media_folder: "/static/img/about"
    public_folder: "/img/about"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "hm"
    label: "HM Page"
    folder: "content/hm"
    create: false
    slug: "index"
    media_folder: "/static/img/hm"
    public_folder: "/img/hm"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "hp"
    label: "HP Page"
    folder: "content/hp"
    create: false
    slug: "index"
    media_folder: "/static/img/hp"
    public_folder: "/img/hp"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "staff"
    label: "Staff Page"
    folder: "content/staff"
    create: false
    slug: "index"
    media_folder: "/static/img/staff"
    public_folder: "/img/staff"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
