backend:
  name: git-gateway
  branch: main

media_folder: "static/img" # Base media folder
public_folder: "/img" # Base public folder
display_url: https://mengo.sirapollokaggwaschools.co.ug/
logo_url: https://mengo.sirapollokaggwaschools.co.ug/img/logo.png

collections:
  - name: "news"
    label: "School Events/News"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    media_folder: "/static/img/posts" # Media files for this collection will be stored in static/img/posts
    public_folder: "/img/posts" # The src attribute for uploaded media will begin with /img/posts
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", default: "", format: "YYYY-MM-DDTHH:mm:ssZ" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "gallery"
    label: "Gallery"
    folder: "static/img/gallery"
    create: true
    media_folder: "/static/img/gallery"
    public_folder: "/img/gallery"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Gallery Images", name: "gallery_images", widget: "list", field: { label: "Image", name: "image", widget: "image" } }
